### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by CWSwastik** [crux-bphc/bits-gpt#1]
# Data collection/parsing

- [ ] PS Chronicles
- [ ] FB Posts (Shoutbox, SMC, FEG, Career Queries)
- [x] Reddit (r/BitsPilani) [Get more posts]
- [x] Handouts
- [ ] Orientation Slides
- [x] BITS Hyd Website
- [ ] Timetable
- [ ] (Optional, low priority) Books, Notes

# Data Formatting/Cleaning

- [x] WITW (pdf to text ruins placement of data which needs to be fixed)
- [ ] Bulletin (Tabular data not being correctly interpreted)  
- [ ] JC Articles (Prune old articles with outdated/wrong info) 
- [x] Clean JC Articles (remove header info, remove html tags?)

# RAG
- [ ] Experiment with the ideal chunk size (currently 1000)
- [ ] Experiment with different embeddings 
- [ ] Switch to Mixtral 7B from GPT 3.5
- [ ] Experiment with the prompt
- [ ] Include date in the metadata and filter by it
- [ ] Set a priority order for sources and filter by it aswell
- [ ] Use a reranker for better results (Possibly)
- [ ] Use query routing for different indexes (Possibly)
- [ ] Use query transformations (Possibly)
- [x] Experiment with different retrievers (https://python.langchain.com/docs/modules/data_connection/retrievers/)
- [x] Implement testing #2

# Issues
- [ ] Including the bulletin in the vector db completly ruins the search results.
- [x] Really bad at reading tabular data even with unstructured
- [ ] Create better summaries of table and text chunks for handouts
